uiwjs/react-codemirror

typings/index.d.ts
Removes duplicate `onCursorActivity` declaration in `typings/index.t.ts`. Duplicate declaration causes error in Typescript compiler.
Closes #45
=> Remove duplicate onCursorActivity type

typings/index.d.ts
Fixes #92 
There's typo/wrong copy paste:
- `onChange` uses `EditorChangeLinkedList`
- `onChanges` uses `EditorChangeLinkedList[]`
=> Fix type definition of `onChange`

README.md, src/index.js, typings/index.d.ts
Hey, thanks for the hard work maintaining this project, it's been super helpful to me so far!
In my set up it doesn't make sense to dynamically load the language resources (modes) at runtime.  I want to have a complete bundle that can be delivered without the need for further network requests.
For this I've added an optional prop, `lazyLoadMode`.  This prop is `true` by default, and if it is `true` nothing changes.  If the prop is `false`, the language resources will not be automatically downloaded and need to be downloaded manually.
The heart of the change is in `src/index.js` line 47.
```diff
-      if (mode && mode.mode) {
+      if (lazyLoadMode && mode && mode.mode) {
```
Just to reiterate, since this prop is `true` by default, this is not a breaking change!
I've updated the types to …
=> Add prop to optionally disable lazy loading language modes

src/index.tsx
I found that if the value is typeof number, the whole page will block and can't be recovery by refresh, all I can do is only close the blocked page and reopen a new page.
I know this library is based on TypeScript, type error will be found in TypeScript's build-time, but it will be better to check value's type manually and throw error let those who using original JavaScript know what problem was happened.
=> fix: Add type checking to value

src/useCodeMirror.ts
Currently the syntax highlighting is broken with `theme="dark"`:
It should instead look like this:
The reason is that the exports in `@codemirror/theme-one-dark` consist of two variables in an array, which
makes up the extension:
https://github.com/codemirror/theme-one-dark/blob/3f6f4e7ec22588df0e8c2777d8ce92889ce811b6/src/one-dark.ts#L134
=> Also use highlight style

README.md
The exports in `@codemirror/theme-one-dark` consist of two variables in an array, which
makes up the extension:
https://github.com/codemirror/theme-one-dark/blob/3f6f4e7ec22588df0e8c2777d8ce92889ce811b6/src/one-dark.ts#L134
Previous PR: https://github.com/uiwjs/react-codemirror/pull/241
cc @arvigeus
=> Fix custom theme docs

src/useCodeMirror.ts
Avoid react warning "An effect function must not return anything besides a function..." for returns non-function result.
=> fix: Avoid react warning for wrong returns from useEffect.

README.md
Comment was being copied along with the command. Removed the comment from the code block
=> Fix Copy to Clipboard Command

core/README.md, core/src/useCodeMirror.ts
I was coming across an issue where I switch between several files in my React app.
As the user switches the file they are editing I change the `value` prop, and the `onUpdate` prop. Roughly like this:
```jsx
const onUpdate = useCallback((viewUpdate) => {
editorStateChanged(filePath, viewUpdate);
}, [filePath]);
<CodeMirror
value={savedFiles.get(filePath).contents}
onUpdate={onUpdate}
/>
```
There are two bugs fixed here:
1.  More of the props encoded into `getExtensions` are watched by the `reconfigure` `useEffect`
2. The `reconfigure` `useEffect` is ordered **before** the `value` `useEffect`
What was happening was:
* `value` change detected by `useEffect` and `view.dispatch` is triggered.
* `view`'s `updateListener` is triggered and the **old** `onUpdate` is called with the contents from …
=> fix(core): add missing attributes to reconfigure useEffect

core/src/index.tsx, core/src/useCodeMirror.ts
Thanks for the great library!
What do you think about adding the way to provide `initialState` property that can be used to initialize the state with [fromJSON](https://codemirror.net/docs/ref/#state.EditorState^fromJSON) function instead of creating it from scratch? This can be helpful to save editor's state with toJSON and restore it when page reloads or component is recreated.
=> Proposal: add an option to provide serialized initial state

core/package.json
I'm having two issues related Phantom Dependency in Yarn berry:
```
✘ [ERROR] Could not resolve "@codemirror/state"
../../node_modules/.store/@uiw-react-codemirror-virtual-d135f79218/node_modules/@uiw/react-codemirror/esm/useCodeMirror.js:2:41:
2 │ import { EditorState, StateEffect } from '@codemirror/state';
╵                                          ~~~~~~~~~~~~~~~~~~~
You can mark the path "@codemirror/state" as external to exclude it from the bundle, which will
remove this error.
✘ [ERROR] Could not resolve "@codemirror/commands"
../../node_modules/.store/@uiw-react-codemirror-virtual-d135f79218/node_modules/@uiw/react-codemirror/esm/useCodeMirror.js:3:30:
3 │ import { indentWithTab } from '@codemirror/commands';
╵                               ~~~~~~~~~~~~~~~~~~~~~~
You can mark the …
```
=> Resolve Phantom Dependency problems

extensions/hyper-link/src/index.ts
In file `extensions/hyper-link/src/index.ts` we have three `console.log`. It was probably not the intention of code.
=> fix: unnecessary console.log

themes/vscode/src/index.ts
Hi @jaywcjlove 👋 Hope you're well!
Just wanted to do a quick PR to add the correct highlighting for JSX component tags, since `@lezer/javascript@>=1.1.0` supports it:
- https://github.com/codemirror/dev/issues/956
- https://github.com/lezer-parser/javascript/releases/tag/1.1.0
VS Code highlights React components with green
**VS Code**
**Theme Before**
**Theme After**
=> Highlight components tag names with green

core/README.md
Apologies if I'm misunderstanding something, but it seems like the doc linked at the top of the README is actually out of date, given that `react-codemirror` is already on version 4.xxxx. This confused me for a bit so to avoid anyone else having the same confusion I propose the link be removed (or otherwise reworded).
=> Remove v3 doc preview given that we're already on v4

core/src/__tests__/index.test.tsx, core/src/useCodeMirror.ts
Do not fire `onChange` handler when codemirror's value is changed from outside (this is how ordinary inputs work). Usually it doesn't matter but when CM is used with async apis it can lead to cycling changes of text
Consider the following example ([sandbox](https://codesandbox.io/s/objective-satoshi-strbtj?file=/src/App.js)):
```js
export default function App() {
const [v, sv] = useState("test");
return (
<>
<input
value={v}
onChange={(e) => {
console.log("input: onChange");
sv(e.target.value);
}}
/>
<CodeMirror
value={v}
onChange={(x) => {
console.log("CodeMirror: onChange");
sv(x);
}}
/>
</>
);
}
```
Here input field and CodeMirror are bound to one state. 
1. When I edit CodeMirror, the input's onChange has not fired and the console output is 
```
> CodeMirror: onChange
```
2. But when …
=> Prevent `onChange` handler from being fired when `value` property is changed from the outside

core/README.md, core/src/index.tsx
The `indentWithTab` prop description in the `ReactCodeMirrorProps` interface was updated to accurately reflect its behavior. 
The description for `indentWithTab` seems to be incorrect, as it duplicated the description of the `basicSetup` prop
- Updated the `indentWithTab` prop description to: 
```ts
Controls whether pressing the `Tab` key inserts a tab character and indents the text (`true`) 
or behaves according to the browser's default behavior (`false`).
```
=> docs: fix indentWithTab prop description

src/index.js
This initializes the textarea in the code editor with the initial value to make the undo history more predictable and intuitive.
=> fix(react-codemirror-merge): fix initial value issue. (uiwjs#489)

extensions/langs/src/index.ts
When I try to build my project with extensions-langs with Vite and TypeScript, it fails.
```
/V/S/r/n/web ❯❯❯  pnpm run build                                                                                                                                                                                            master ✱
> web@0.0.0 build /Volumes/SN570/repos/ntoj/web
> tsc && vite build
node_modules/.pnpm/@uiw+codemirror-extensions-langs@4.21.12_@codemirror+autocomplete@6.8.1_@codemirror+language-_ek6k5ykpbfm47cmo3hp4vptutq/node_modules/@uiw/codemirror-extensions-langs/src/index.ts:33:3 - error TS6133: 'clike' is declared but its value is never read.
33   clike,
~~~~~
Found 1 error in node_modules/.pnpm/@uiw+codemirror-extensions-langs@4.21.12_@codemirror+autocomplete@6.8.1_@codemirror+lan …
```
=> remove `clike` import

themes/theme/src/index.tsx
When you use the drawSelection() extension, it hides the current selection through:
```
& .cm-line ::selection {
background-color: transparent !important;
}
```
However, we were styling selections using:
```
&.cm-focused .cm-line ::selection {
background-color: <some background color> !important;
}
```
Since our style is more selective, it takes precedence over the original style that was supposed to hide the current selection. As a result, if you use drawSelection(), the selection would be highlighted twice, once through ```.cm-selectionBackground``` and once through ```.cm-line::selection```.
=> Fix double highlighting selection when using drawSelection.

core/README.md, themes/theme/README.md, themes/theme/src/index.tsx, www/src/pages/theme/editor/themeCode.ts
In all READMEs and the theme editor page, I added `backgroundImage: '',` to show people that the option exists. I don't think we need a background image customizing option on the theme editor page (a text box would look weird next to the color selectors), but let me know if you think otherwise.
=> Add background image option to createTheme()

extensions/hyper-link/src/index.ts
Changes made:
1. Replaced the usage of syntaxTree with a regular expression to match URLs in the document text.
=> Remove dependency on syntaxTree for hyperlink decorations

www/src/pages/home/Example.tsx
The code editor on the home page is being cut off.
Full disclosure, I've only tested this by remving the style through inspector.
=> Remove margin from Example.tsx causing it to be cut off

www/src/pages/home/index.tsx
Issue: The visibility of the BackToUp component was affected by the stacking order on the homepage.
Solution: Reordered the placement of the BackToUp component to make it  visible element on the page without adjusting z-index property, resolving the visibility issue. This change enhances the user experience by ensuring the BackToUp button is prominently displayed.
This is my first open-source contribution, and I'm open to feedback. Please review, and let me know if there are any additional adjustments required. Thank you!
=> Move BackToUp component to the end for improved visibility

core/README.md, themes/console/README.md, themes/console/dark.d.ts, themes/console/light.d.ts, themes/console/package.json, themes/console/src/dark.ts, themes/console/src/index.ts, themes/console/src/light.ts, themes/console/tsconfig.json, www/src/router.tsx
I have added the `console` theme to use the react-codemirror as a logger component in our react applications.
I can start using this theme in my project.
Images are still missing, how could I add those?
**Dark**
**Light**
Please review
=> feat(theme): add `console` theme

core/src/useCodeMirror.ts
Closes #474 
I don't know if we should merge this PR (I didn't find a better solution to avoid `null` type).
=> fix: correct type of `container` returned from `useCodeMirror`

core/.kktrc.ts
The JSX runtime is currently being bundled which is generally not supported. The JSX runtime needs to be in lockstep with the React version.
This currently breaks in React 19 because the bundled JSX runtime tries to access secret internals that have been moved.
=> Externalize JSX runtime

themes/vscode/src/light.ts
Changed the line highlight color in the VSCode Light theme to #99999926.
It is now the same as the original color #f0f0f0 due to the opacity, and now the selected text at the highlighted line is visible.
before
after
=> theme: Vscode Light - lineHighlight

extensions/hyper-link/src/index.ts
There's a memory leak in the `hyper-link` extension which will reliably crash a Chrome tab. To reproduce, go to to [the documentation page](https://uiwjs.github.io/react-codemirror/#/extensions/hyper-link) in Chrome and paste in `https://www.npmjs.com/package/@uiw/react-codemirror` 3000-4000 times. You can paste them all at once or a couple hundred at a time.
Here's a recording of the crash:
https://github.com/user-attachments/assets/9b6550a4-7a83-4a26-bad1-a17087a22ec7
The issue here is that when `doc.toString()` is in the while loop, a new string is created of the entire document, and Chrome creates a [sliced string](https://developer.chrome.com/docs/devtools/memory-problems/heap-snapshots#sliced-string) when running `defaultRegexp.exec`. That sliced string has a `parent` reference back …
=> (fix): Memory leak in hyper-link extension

core/package.json, extensions/basic-setup/package.json
Added exports field to the core (@uiw/react-codemirror) and basic setup (@uiw/codemirror-extensions-basic-setup) package.json so Node-like environments such as the test runners can utilise the esm outputs.
Context:
Our unit tests are failing with:
```
Unrecognized extension value in extension set ([object Object]). This sometimes happens because multiple instances of @codemirror/state are loaded, breaking instanceof checks.
```
After some investigation, it looks like when this library is used in a Node environment all imports use the cjs output. `main` and `module` are already defined and work for bundlers. However, Node doesn't have support for `module` and opts to look in `exports` for entry points. Since `exports` is not defined it falls back to `main` meaning Node will use the cjs …
=> Implement 'exports' field in package.json for the core & basics setup packages

merge/src/Internal.tsx
The `diffConfig` prop is defined in the `MergeConfig` interface but is incorrectly spread onto the `<div>` element instead of being passed to the editor options.
This prevents customization of the `diffConfig` parameter.
This PR correctly passes the `diffConfig` prop to the mergeConfig options, enabling proper customization.
=> fix: Pass `diffConfig` to options in `CodeMirrorMerge` component

themes/basic/src/light.ts
Correctly extends the base theme for the theme `basic`.
=> fix(theme): correctly extend basic light theme

extensions/basic-setup/package.json
I am getting errors about this package not having `type: module`, hence imports don't work. This line fixes it. Lemme know if you'd like me to do so for the other packages too
=> type: module in codemirror-extensions-basic-setup

core/src/index.tsx, core/src/useCodeMirror.ts, www/src/pages/home/Example.tsx
Does two things to eliminate the flash, when using the `ReactCodeMirror` component:
1. Eliminate one initial re-render from calling `setContainer` in an effect when the `container` prop changes
- previously, this resulted in `setContainer(null)` -> re-render -> `setContainer(el)` -> re-render -> [now component can initialize]
- now, the first effect invocation no-ops, since the ref value is not truthy, then the second time no state is updated, since `props.container` is referentially equal to `container`, set by the ref callback when the `div` mounted
2. Eliminate one paint by running initialization in a layout effect, which forces the second re-render to occur synchronously before paint
So the new set of render cycles on mount is:
mount -> `setContainer` in callback ref -> re-render -> …
=> Fix flash of content on initialization 

extensions/basic-setup/package.json
This is a fix/workaround for the CommonJS/esm issue.
The root cause was adding the `exports` fields in `package.json`. Before it was introduced, Node.js would pick up what is defined in the `main` field (cjs)  and bundlers used the `module` field (esm). When the `exports` field was introduced, Node.js started picking up the esm version too, but is nagging about no `types` field in `package.json`. After the `types` field was added, commonjs in bundlers is not working anymore because `package.json` says that all `.js` files in the package are ESM.
Possibilities:
- Remove `exports` and `type` fields in package.json 
- Add 2 new `package.json` files and define the type correctly for the generated files. (What this PR does)
Fixes #724 
Fixes #719 
Ref #710 
Ref #680
=> fix: Set correct module type in basic package

core/.babelrc, core/package.json
This fixes issues from https://github.com/uiwjs/react-codemirror/issues/731.
Here is the codesandbox that implements this https://codesandbox.io/p/github/Shellishack/webpack-esm-sandbox/fork-fix. After adding the babel plugin, core builds for ESM contains ".js" suffix in import clauses. So webpack no longer complains things like:
```
ERROR in ./node_modules/@uiw/react-codemirror/esm/index.js 5:0-48
Module not found: Error: Can't resolve './useCodeMirror' in 'C:\GitHub\pulse-editor-code-view\node_modules\@uiw\react-codemirror\esm'
Did you mean 'useCodeMirror.js'?
``` 
This might be a fix only for Webpack (I am only familiar with Webpack). May need more testing for Vite, etc.
I am sure if adding a babel plugin in this case would be the most appropriate solution, since it was the building …
=> Fix ESM import in core package by adding .babelrc and babel-plugin-add-import-extension

core/src/useCodeMirror.ts
Consider an example:
an app has table of content (ToC) and an editor. Clicking on a table of content item selects and scrolls into view the clicked section.
moving cursor to another section with arrow keys highlights corresponding ToC item.
This requires sending selection changes to CM6 and listening for selection changes.
When ToC is clicked the app triggers an update, and immediately receives the onChange with the same update.
Distinguishing between changes triggered by user and by app itself can be done on the app side, but it's a lot of unnecessary complex logic.
Or, if the app had access to the External annotation it could simply tell useCodeMirror to ignore the change.
This is the motivation behind this PR.
=> Add External annotation to the public API

extensions/langs/src/index.ts
we use the the typing of languageName which was break in the last version from union type to string
With sastifiy i still check that my value have the right type but keep the right typing for my users.
https://github.com/scaleway/ultraviolet/blob/main/packages/plus/src/components/CodeEditor/CodeEditor.tsx#L110
Actually 
@jaywcjlove
=> fix(extensions): typing issue string instead of an union type
